### ISSUE TITLE
Not defined fsType causes volumes are mounted with root permission only

### ISSUE THREAD

**Issue by megian** [cloudscale-ch/csi-cloudscale#26]
### What did you do?

After installing the CSI Plugin on OpenShift 4.7 new created volumes couldn't be accessed. Same on a regular Kubernetes cluster didn't show that behavior.

I've figured out: With version 2.0 the external provisioner has removed the default
fsType [1]. With no filesystem set, Kubernetes does not set the
group ID and this causes volumes are mounted with root permissions
only [2]. Some distributions like OpenShift disallow access in this case.

```
# ls -l /var/lib/kubelet/pods/c50571e0-cd19-4e1b-a724-1da3b994f740/volumes/kubernetes.io~csi/pvc-41e303f6-4aa9-43db-9d50-c9d4102f6208/
total 8
drwxr-xr-x. 5 root root 4096 Jun 18 13:21 mount
-rw-r--r--. 1 root root  290 Jun 18 13:05 vol_data.json
```

[1] https://github.com/kubernetes-csi/external-provisioner/blob/master/CHANGELOG/CHANGELOG-2.0.md#changelog-since-v160
[2] NetApp/trident#556 (comment)

### How it should look like

```
# ls -l /var/lib/kubelet/pods/d49c9a5e-b5b9-41c1-ae48-26ed19db1c4f/volumes/kubernetes.io~csi/pvc-69fb7bd4-0bf0-433e-9d43-d442534e9d97/mount/
total 20
drwxrwsr-x. 4 1000570000 1000570000  4096 Oct 22  2020 elasticsearch
drwxrws---. 2 root       1000580000 16384 Oct 22  2020 lost+found
```

### Configuration

* CSI Version: 2.1.0
* Kubernetes Version: 1.20

### Summary

I think it's recommendable to set a file system type for all Kubernetes clusters. Adding this the upgrade procedure or direct in the manifests, would help prevent other's run into the same issue.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cloudscale-volume-ssd
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.cloudscale.ch
allowVolumeExpansion: true
parameters:
  csi.cloudscale.ch/volume-type: ssd
  fsType: ext4 <====
```
